# NumPy 기초

NumPy의 주요한 객체는 다차원의 동종 배열(homogeneous nultidimensional array)입니다. 보통은 숫자인 요소들의 집합이며, 모두 같은 타입을 갖습니다.

NumPy에서 차원은 축(axis)이라고 합니다.

예를 들어, 3차원 공간에서 점[1,2,1]의 좌표는 하나의 축(axis)을 갖습니다. 이 축은 3개의 요소를 가지고 길이는 3입니다.

아래의 예에서, 배열은 두 개의 축을 갖는데, 첫번째 축은 길이가 2, 두번째 축은 길이가 3입니다.

In [ ]:
[[1., 0., 0.],
 [0., 1., 2.]]

Numpy의 배열 클래스는 ndarray라고 합니다.

numpy.array는 표준 파이썬 라이브러리의 클래스인 array.array와 다릅니다. array.array는 1차원 배열만 다루고, 더 적은 기능을 제공합니다.

ndarray 객체의 중요한 속성은 다음과 같습니다:

__ndarray.ndim__  
배열 축의 개수(차원)

__ndarray.shape__  
배열의 차원. 각 차원의 배열의 크기를 나타내는 정수의 튜플.  
n개의 행, m개의 열을 갖는 행렬의 경우, shape은 (n,m). 따라서 shape 튜플의 길이는 축의 개수가 됨.

__ndarray.size__  
배열의 요소의 총 개수. shape 튜플의 요소의 곱과 같음.

__ndarray.dtype__  
배열의 요소의 타입을 나타내는 객체. 표준 파이썬 타입을 이용해서 dtype을 만들거나 지정할 수 있음.  
이 외에도 NumPy는 numpy.int32, numpy.int16, numpy.float64와 같은 고유한 타입을 제공함.

__ndarray.itemsize__  
배열의 각 요소의 바이트 크기. 예를 들어, float64 타입의 요소를 갖는 어레이는 itemsize가 8(64/8).  
complex32 타입을 갖는 배열의 itemsize는 4(=32/8). ndarray.dtpye.itemsize와 같음.

__ndarray.data__  
배열의 실제 요소를 갖는 버퍼. 보통, 인덱스 기능을 이용해서 배열의 요소에 접근하기 때문에 이 속성을 사용할 필요가 없을 것임.

## 예제

In [2]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print('a.shape:', a.shape)            # 배열의 차원
print('a.ndim:', a.ndim)              # 배열의 축의 개수
print('a.dtype.name:', a.dtype.name)  # 배열의 요소의 타입
print('a.itemsize:', a.itemsize)      # 배열 요소의 바이트 크기
print('a.size:', a.size)              # 배열의 요소의 총 개수
print('type(a):', type(a))            # 배열의 타입

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape: (3, 5)
a.ndim: 2
a.dtype.name: int32
a.itemsize: 4
a.size: 15
type(a): <class 'numpy.ndarray'>
