# NumPy 배열 형태 다루기
NumPy 배열의 형태를 다루는 방법(shape manipulation)에 대해 알아봅니다.

우선 배열을 형태를 확인하고(`shape`), 변경하고(`reshape()`), 행과 열을 바꾸는(`T`) 방법에 대해 알아봅니다.

그리고 `vstack()`, `hstack()`, `column_stack()`을 이용해서 배열을 함치는 방법,  
`hsplit()`을 이용해서 배열을 쪼개는 방법에 대해서도 알아봅시다.

## Contents
* 목차
(:toc}

# 배열 행태 바꾸기
배열은 각 축에 대한 요소의 개수로 주어지는 형태(shape)를 가집니다.

배열의 형태를 확인하고, 원하는 형태로 바꾸는 방법에 대해 알아봅니다.

## ndarray.shape
배열의 형태를 반환합니다.

In [3]:
import numpy as np

a = np.floor(10*np.random.random((3,4)))

print(a)
print(a.shape)

[[ 1.  6.  2.  4.]
 [ 8.  4.  0.  3.]
 [ 7.  9.  0.  3.]]
(3, 4)


배열 a의 형태는 (3,4)입니다.

배열의 형태는 다양한 명령을 통해 바꿀 수 있습니다.

다음의 세가지 명령은 수정된 배열을 반환하지만 원래 배열은 변경하지 않습니다.

## ndarray.ravel()
```ravel()```은 (1차원으로) 펼쳐진 배열을 반환합니다.

In [4]:
import numpy as np

a = np.floor(10*np.random.random((3,4)))

print(a.ravel())

[ 4.  5.  5.  7.  8.  7.  8.  5.  9.  7.  8.  2.]


## ndarray.reshape()
새로운 형태를 갖는 배열을 반환합니다.

In [5]:
import numpy as np

a = np.floor(10*np.random.random((3,4)))

print(a.reshape(6, 2))

[[ 5.  6.]
 [ 1.  7.]
 [ 8.  8.]
 [ 0.  3.]
 [ 2.  3.]
 [ 4.  5.]]


## ndarray.T
행과 열을 바꾼 전치행렬 배열(transposed array)를 반환합니다.

In [6]:
import numpy as np

a = np.floor(10*np.random.random((3,4)))

print(a.T)

[[ 8.  1.  8.]
 [ 6.  5.  4.]
 [ 1.  1.  0.]
 [ 0.  6.  6.]]


# 배열 합치기
여러 배열을 하나의 배열로 합칠 수 있는 `vstack()`, `hstack()`, `column_stack()`의 사용법에 대해 알아봅니다.

## numpy.vstack()
`vstack()`은 배열을 수직 방향으로(행을 따라서) 합칩니다.

In [9]:
import numpy as np

a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a, '\n')
print(b, '\n')
print(np.vstack((a,b)))

[[ 8.  1.]
 [ 2.  6.]] 

[[ 3.  5.]
 [ 5.  7.]] 

[[ 8.  1.]
 [ 2.  6.]
 [ 3.  5.]
 [ 5.  7.]]


## numpy.hstack()
`hstack()`은 배열을 수평 방향으로(열을 따라서) 합칩니다.

In [10]:
import numpy as np

a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a, '\n')
print(b, '\n')
print(np.hstack((a,b)))

[[ 3.  5.]
 [ 5.  8.]] 

[[ 5.  3.]
 [ 0.  2.]] 

[[ 3.  5.  5.  3.]
 [ 5.  8.  0.  2.]]


## numpy.column_stack()
`column_stack()`은 1차원 배열을 열 방향으로 세워서 2차원 배열로 만듭니다.

In [12]:
import numpy as np

np.random.seed(0)

a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(np.hstack((a,b)), '\n')
print(np.column_stack((a,b)))

[[ 5.  7.  4.  6.]
 [ 6.  5.  4.  8.]] 

[[ 5.  7.  4.  6.]
 [ 6.  5.  4.  8.]]


2차원 배열에 대해서는 `hstack()`과 기능이 동일합니다.

In [13]:
a = np.array([4, 2])
b = np.array([2, 8])

print(np.hstack((a,b)), '\n')
print(np.column_stack((a,b)))

[4 2 2 8] 

[[4 2]
 [2 8]]


하지만 1차원 배열에 대해서 `hstack()`과 `column_stack()`은 다른 결과를 반환합니다.

# 배열 쪼개기

`hsplit()`을 이용해서 수평 방향으로 배열을 쪼갤 수 있습니다.

동일한 형태로 나눠질 배열의 개수를 지정하거나, 어떤 열(column)에서 나눌지 지정할 수 있습니다.

## 동일한 형태로 나누기

In [15]:
import numpy as np

a = np.floor(10*np.random.random((2,12)))

print(a, '\n')
print(np.hsplit(a, 3))

[[ 4.  5.  0.  6.  6.  6.  9.  6.  3.  4.  6.  0.]
 [ 6.  6.  2.  1.  3.  3.  5.  4.  9.  1.  2.  1.]] 

[array([[ 4.,  5.,  0.,  6.],
       [ 6.,  6.,  2.,  1.]]), array([[ 6.,  6.,  9.,  6.],
       [ 3.,  3.,  5.,  4.]]), array([[ 3.,  4.,  6.,  0.],
       [ 9.,  1.,  2.,  1.]])]


`np.hsplit(a, 3)`은 배열 a를 3개의 동일한 형태의 배열로 나눈 배열을 반환합니다.

## 나눌 열(column) 지정하기

In [17]:
import numpy as np

a = np.floor(10*np.random.random((2,12)))

print(a, '\n')
print(np.hsplit(a, (3, 4)))

[[ 3.  4.  0.  6.  5.  2.  5.  0.  5.  9.  3.  6.]
 [ 1.  7.  2.  1.  5.  0.  8.  0.  6.  2.  7.  9.]] 

[array([[ 3.,  4.,  0.],
       [ 1.,  7.,  2.]]), array([[ 6.],
       [ 1.]]), array([[ 5.,  2.,  5.,  0.,  5.,  9.,  3.,  6.],
       [ 5.,  0.,  8.,  0.,  6.,  2.,  7.,  9.]])]


`np.hsplit(a, (3, 4))`은 배열 a를 세 번째 열 이후, 그리고 네 번째 열 이후에서 쪼갠 세개의 배열을 갖는 배열을 반환합ㄴㅣ다.